### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by captainhowdy1** [brianwarehime/truepeoplesearch_transforms#2]
Unable to run transforms due to a list index out of range error 
`Traceback (most recent call last):
  File "truepeoplesearch.py", line 51, in <module>
    url = args.split("url=")[1]
IndexError: list index out of range`
result is using Maltego CE 4.1.14, fresh setup, entity person has the address property added.

**Comment by CodeXTF2** [comment]
Traceback (most recent call last):
  File "truepeoplesearch.py", line 51, in <module>
    url = args.split("url=")[1]
IndexError: list index out of range

Fresh install of maltego
